{
    "type": "object",
    "required": ["server"],
    "properties": {
        "global": {
            "type": "object",
            "required": ["aws_region","s3_endpoint_url"],
            "properties": {
                "aws_region": {"type": "string","default": "us-east-1"},
                "log_level": {"type": "number", "default", 3},
                "s3_endpoint_url": {"type": "string"},
            },
            "additionalProperties": False
        },
        "server": {
            "type": "object",
            "properties": {
                "host": {"type": "string","default": "0.0.0.0"},
                "port": {"type": "number","default": "80"},
                "chunk_size": {"type": "number","default": "1280000"},
                "debug": {"type": "boolean","default": False},
                "tcp_keepalive": {"type": "boolean","default": True},
                "shutdown_timeout": {"type": "string","default": "30.0"},
                "backlog": {"type": "number","default": 128},
                "reuse_address": {"type": "boolean","default": True},
                "reuse_port": {"type": "boolean","default": True},
                "keepalive_timeout": {"type": "number","default": 30},
                "max_line_size": {"type": "number","default": 8190},
                "max_headers": {"type": "number","default": 32768},
                "max_field_size": {"type": "number","default": 8190},
                "lingering_time": {"type": "number","default": 0},
                "client_max_size": {"type": "number","default": 104857600},
            },
            "additionalProperties": False
        },
    },
}